server.error.whitelabel.enabled: true
server:
    port: ${PORT:8000}
    connection-timeout: 30000
    context-path: /v2
biblia:
    teste:
        nome: EversonTestandoApplication 
spring:
    pid:
        fail-on-write-error: false
        file: pier.pid
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: none
            properties:
                hibernate.jdbc.time_zone: America/Sao_Paulo
            envers:
                auditTableSuffix: _AUD
    datasource:
        url: jdbc:mysql://${HOST_DB:localhost}:${HOST_PORT_DB:3306}/${DATA_BASE:abiblia}?useSSL=false
        username: ${USER_DB:root}
        password: ${USER_PASSWORD:123456}
        testWhileIdle: true
        validationQuery: SELECT 1
endpoints:
    health:
        sensitive: false